from __future__ import annotations

import base64


def _fixture(value: str) -> bytes:
    return base64.b64decode("".join(value.split()))


SUGAAR = _fixture("""
AQIERE9NHWICAHwCAAAAAAAAAAAAAP////89AAAAAAAAAAAAAAAhKjgjID0rPE94eAAAAAACMQAAAAAAAL0BAAAA
AAAAAAAAAAAAAAAAAAAAAAQAAAAAAAD/////Ng9zAP////8AAHwCAAAAAAAAAAAAAAAAAAAAAAAAUgc9AP////8A
AAAAAAAAAAAAAP////82DwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHDooLi49TwIAAAD/////////////////////////
/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////AAAAAAAAAAYG
BgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACMf7/AAAAAE8BAAAAAAAA
AAAAAAAEAAAAAAAAAAcAAAAGAAAAAwAAAAMAAAAcOiguLj1PT0+sC3sAAAAGBgAAAAAAAAAAiVoAAAOF
""")

WEEPING_ONE = _fixture("""
AQIERE9NHWICAHwCAAAAAAAAAAAAAP////8HAAAAAAAAAAAAAAAhKjgjID0rPE94eAAAAAACMQAAAAAAAL0BAAAA
AAAAAAAAAAAAAAAAAAAAAAQAAAAAAAD/////kAIjAP////8AAHwCAAAAAAAAAAAAAAAAAAAAAAAA7QcHAP////8A
AAAAAAAAAAAAAP////+QAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGwcKbxgKCh8GAQhvAAEKTwAAAAD/////////////
/////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////
AAAAAAAAAAgAAAAAAAAIAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACMQMAAP3+
/k8CAAAAAAAAAAAAAAAIAAAAAAAAAFUAAABWAAAAUgAAAFIAAABSAAAAUgAAAFIAAAA/AAAAGwcKbxgKCh8GAQhv
AAEKT09PrAt7AAAAAAAAAAAACAAIAIlaAAAxLA==
""")
